[package]
name = "joseph/spin-rhythm"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fluid = "ffrostfall/fluid@0.6.4"
Charm = "littensy/charm@0.11.0"
CharmSync = "littensy/charm-sync@0.4.0"
